<a href="https://colab.research.google.com/github/rat145/pw_assignments/blob/main/feature_engg_assignment_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its application.

In [3]:
'''
1. Min Max scaler is a normalization technique used in datasets to scale data.
2. It's value lies from 0 to 1.
3. The more the value is towards 0, the more it is close to minimum value.
4. The more the value is towards 1, the more it is close to maximum value.
'''

In [5]:
# importing min max scaler from sklearn.preprocessing library
from sklearn.preprocessing import MinMaxScaler

In [6]:
# creating an instance of minmaxscaler
min_max = MinMaxScaler()

In [7]:
import seaborn as sns
df = sns.load_dataset("tips")
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
# Lets apply normalization on total_bill feature.
min_max.fit_transform(df[['total_bill']])

array([[0.29157939],
       [0.1522832 ],
       [0.3757855 ],
       [0.43171345],
       [0.45077503],
       [0.46543779],
       [0.11939673],
       [0.49874319],
       [0.25073314],
       [0.24528697],
       [0.15081693],
       [0.67427734],
       [0.25869292],
       [0.32174277],
       [0.24633431],
       [0.38772518],
       [0.15207373],
       [0.27691663],
       [0.29116045],
       [0.36824466],
       [0.31105991],
       [0.36070381],
       [0.2660243 ],
       [0.761416  ],
       [0.35085882],
       [0.30875576],
       [0.21575199],
       [0.20150817],
       [0.39023879],
       [0.34729786],
       [0.13573523],
       [0.32006703],
       [0.25115207],
       [0.36908253],
       [0.30812736],
       [0.43967323],
       [0.27733557],
       [0.29032258],
       [0.32718894],
       [0.59069962],
       [0.27167993],
       [0.30142438],
       [0.22769166],
       [0.13845832],
       [0.57247591],
       [0.31881022],
       [0.40134059],
       [0.614

In [9]:
bill_normalized_array = min_max.fit_transform(df[['total_bill']])

In [14]:
import pandas as pd
# Lets add it in the dataframe
df_normalized = pd.DataFrame(bill_normalized_array, columns = ['total_bill_scaled'])
df_normalized.head()

total_bill_scaled
0           0.291579
1           0.152283
2           0.375786
3           0.431713
4           0.450775

In [15]:
pd.concat([df,df_normalized], axis = 1)

total_bill   tip     sex smoker   day    time  size  total_bill_scaled
0         16.99  1.01  Female     No   Sun  Dinner     2           0.291579
1         10.34  1.66    Male     No   Sun  Dinner     3           0.152283
2         21.01  3.50    Male     No   Sun  Dinner     3           0.375786
3         23.68  3.31    Male     No   Sun  Dinner     2           0.431713
4         24.59  3.61  Female     No   Sun  Dinner     4           0.450775
..          ...   ...     ...    ...   ...     ...   ...                ...
239       29.03  5.92    Male     No   Sat  Dinner     3           0.543779
240       27.18  2.00  Female    Yes   Sat  Dinner     2           0.505027
241       22.67  2.00    Male    Yes   Sat  Dinner     2           0.410557
242       17.82  1.75    Male     No   Sat  Dinner     2           0.308965
243       18.78  3.00  Female     No  Thur  Dinner     2           0.329074

[244 rows x 8 columns]

### Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.

In [ ]:
'''
1. Unit vectors are those vectors which have magnitude 1.
2. The Unit Vector technique, also known as Normalization, is a feature scaling technique that scales each feature to have a magnitude of 1.
3. It is useful when we want to preserve the direction of the data without emphasizing the magnitude of each feature.
4. In contrast, Min-Max scaling scales each feature to a given range, typically between zero and one.
'''

In [16]:
from sklearn.preprocessing import normalize

In [21]:
df = sns.load_dataset("diamonds")
df.head()

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75

In [22]:
df.columns

Index(['carat', 'cut', 'color', 'clarity', 'depth', 'table', 'price', 'x', 'y',
       'z'],
      dtype='object')

In [23]:
normalize(df[['depth', 'table']])

array([[0.74539979, 0.6666177 ],
       [0.700048  , 0.71409579],
       [0.6586685 , 0.75243326],
       ...,
       [0.72304181, 0.69080427],
       [0.72470275, 0.68906163],
       [0.74913448, 0.66241795]])

In [24]:
df_unit_vector = pd.DataFrame(normalize(df[['depth', 'table']]), columns = ['normalized_depth','normalized_table'])
df_unit_vector.head()

normalized_depth  normalized_table
0          0.745400          0.666618
1          0.700048          0.714096
2          0.658668          0.752433
3          0.732459          0.680811
4          0.737299          0.675566

In [25]:
pd.concat([df, df_unit_vector], axis = 1)

carat        cut color clarity  depth  table  price     x     y     z  \
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43   
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31   
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31   
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63   
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75   
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...   
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50   
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61   
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56   
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74   
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64   

       normalized_depth  normalized_table  
0              0.745400          0.666618  
1              0.700048          0.714096  
2              0.658668          0.752433  
3              0.732459          0.680811  
4              0.737299          0.675566  
...                 ...               ...  
53935          0.729537          0.683941  
53936          0.753833          0.657066  
53937          0.723042          0.690804  
53938          0.724703          0.689062  
53939          0.749134          0.662418  

[53940 rows x 12 columns]

### Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.

In [ ]:
'''
**Principal Component Analysis (PCA)** is a statistical technique used for **dimensionality reduction**¹. It aims to transform a dataset with a large number of variables into a new set of variables called **principal components**¹. These principal components are linear combinations of the original variables and are ordered in decreasing order of importance¹.

PCA is used to reduce the dimensionality of a dataset while preserving the most important patterns or relationships between the variables¹. It is widely used in exploratory data analysis and machine learning for predictive models¹. By reducing the number of dimensions, PCA helps to address the **curse of dimensionality**, which refers to issues such as overfitting, increased computation time, and reduced accuracy that arise when working with high-dimensional data¹.

Here's an example to illustrate how PCA works. Let's say we have a dataset with three features: `x`, `y`, and `z`. We want to reduce the dimensionality of this dataset using PCA. The original dataset looks like this:

| **x** | **y** | **z** |
|-------|-------|-------|
| 2     | 4     | 6     |
| 3     | 6     | 9     |
| 4     | 8     | 12    |

To apply PCA, we first calculate the covariance matrix of the original dataset. Then, we find the eigenvectors and eigenvalues of this covariance matrix. The eigenvectors represent the principal components, and the eigenvalues represent the amount of variance explained by each principal component.

In this example, let's assume that the eigenvectors and eigenvalues are as follows:

- Eigenvector 1: [0.2673, 0.5345, 0.8018]
- Eigenvector 2: [0.5345, -0.8018, 0.2673]
- Eigenvector 3: [0.8018, 0.2673, -0.5345]
- Eigenvalue 1: 30
- Eigenvalue 2: 10
- Eigenvalue 3: 5

We can see that the first eigenvector (PC1) captures the maximum amount of variance in the data, followed by PC2 and PC3. Therefore, we can choose to retain only PC1 if we want to reduce the dimensionality to one.

The transformed dataset using PCA would look like this:

| **PC1** |
|---------|
| -2.6832 |
| -5.3664 |
| -8.0496 |

As you can see, we have successfully reduced the dimensionality from three features (`x`, `y`, `z`) to one principal component (`PC1`).
'''

### Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept.

In [ ]:
'''
**Principal Component Analysis (PCA)** is a statistical technique used for **dimensionality reduction**¹. It aims to transform a dataset with a large number of variables into a new set of variables called **principal components**¹. These principal components are linear combinations of the original variables and are ordered in decreasing order of importance¹.

PCA is used to reduce the dimensionality of a dataset while preserving the most important patterns or relationships between the variables¹. It is widely used in exploratory data analysis and machine learning for predictive models¹. By reducing the number of dimensions, PCA helps to address the **curse of dimensionality**, which refers to issues such as overfitting, increased computation time, and reduced accuracy that arise when working with high-dimensional data¹.

Here's an example to illustrate how PCA works. Let's say we have a dataset with three features: `x`, `y`, and `z`. We want to reduce the dimensionality of this dataset using PCA. The original dataset looks like this:

| **x** | **y** | **z** |
|-------|-------|-------|
| 2     | 4     | 6     |
| 3     | 6     | 9     |
| 4     | 8     | 12    |

To apply PCA, we first calculate the covariance matrix of the original dataset. Then, we find the eigenvectors and eigenvalues of this covariance matrix. The eigenvectors represent the principal components, and the eigenvalues represent the amount of variance explained by each principal component.

In this example, let's assume that the eigenvectors and eigenvalues are as follows:

- Eigenvector 1: [0.2673, 0.5345, 0.8018]
- Eigenvector 2: [0.5345, -0.8018, 0.2673]
- Eigenvector 3: [0.8018, 0.2673, -0.5345]
- Eigenvalue 1: 30
- Eigenvalue 2: 10
- Eigenvalue 3: 5

We can see that the first eigenvector (PC1) captures the maximum amount of variance in the data, followed by PC2 and PC3. Therefore, we can choose to retain only PC1 if we want to reduce the dimensionality to one.

The transformed dataset using PCA would look like this:

| **PC1** |
|---------|
| -2.6832 |
| -5.3664 |
| -8.0496 |

As you can see, we have successfully reduced the dimensionality from three features (`x`, `y`, `z`) to one principal component (`PC1`).
'''

### Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to preprocess the data.

In [27]:
# Lets first create a sample data set
import numpy as np

data = {
    "Product_price_$": np.random.randint(10,50,size=100),
    "Rating": np.random.randint(1,6,size=100),
    "Delivery_time_minutes": np.random.randint(10,60,size=100)
}

df = pd.DataFrame(data)
df.head()

Product_price_$  Rating  Delivery_time_minutes
0               43       2                     10
1               30       3                     16
2               20       1                     26
3               39       3                     32
4               47       1                     18

In [29]:
df.columns

Index(['Product_price_$', 'Rating', 'Delivery_time_minutes'], dtype='object')

In [30]:
scaler = MinMaxScaler()

In [31]:
scaler.fit_transform(df[['Product_price_$', 'Rating', 'Delivery_time_minutes']])

array([[0.84615385, 0.25      , 0.        ],
       [0.51282051, 0.5       , 0.12244898],
       [0.25641026, 0.        , 0.32653061],
       [0.74358974, 0.5       , 0.44897959],
       [0.94871795, 0.        , 0.16326531],
       [0.53846154, 0.75      , 0.65306122],
       [0.17948718, 0.5       , 0.36734694],
       [1.        , 1.        , 0.32653061],
       [0.41025641, 0.        , 0.83673469],
       [0.51282051, 0.        , 0.83673469],
       [0.51282051, 0.        , 0.04081633],
       [0.92307692, 0.25      , 0.36734694],
       [0.66666667, 1.        , 0.44897959],
       [0.41025641, 0.25      , 0.87755102],
       [0.71794872, 0.5       , 1.        ],
       [0.48717949, 1.        , 0.10204082],
       [0.30769231, 0.25      , 0.24489796],
       [0.79487179, 0.        , 0.79591837],
       [0.87179487, 0.75      , 0.        ],
       [0.58974359, 0.25      , 0.65306122],
       [0.53846154, 0.        , 0.71428571],
       [0.25641026, 0.75      , 0.55102041],
       [0.

In [35]:
scaled_data = scaler.fit_transform(df[['Product_price_$', 'Rating', 'Delivery_time_minutes']])

In [36]:
scaled_df = pd.DataFrame(scaled_data, columns = ['price_scaled','rating_scaled','delivery_time_scaled'])

In [37]:
scaled_df.head()

price_scaled  rating_scaled  delivery_time_scaled
0      0.846154           0.25              0.000000
1      0.512821           0.50              0.122449
2      0.256410           0.00              0.326531
3      0.743590           0.50              0.448980
4      0.948718           0.00              0.163265

### Q6. You are working on a project to build a model to predict stock prices. The dataset contains many features, such as company financial data and market trends. Explain how you would use PCA to reduce the dimensionality of the dataset.

In [38]:
import pandas as pd
import numpy as np

# Create a dictionary with the data
data = {'Company': ['A', 'B', 'C', 'D'],
        'Revenue': np.random.randint(100000, 1000000, size=4),
        'Profit': np.random.randint(10000, 100000, size=4),
        'Market Share': np.random.uniform(0.1, 0.5, size=4),
        'Growth Rate': np.random.uniform(0.01, 0.1, size=4)}

# Create a pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Print the DataFrame
print(df)

  Company  Revenue  Profit  Market Share  Growth Rate
0       A   147157   35333      0.256848     0.033110
1       B   207004   11927      0.149418     0.055810
2       C   224595   44670      0.379824     0.089645
3       D   359374   70602      0.216393     0.079265


In [39]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

features_to_scale = ['Revenue', 'Profit', 'Market Share', 'Growth Rate']
scaler = StandardScaler()
df[features_to_scale] = scaler.fit_transform(df[features_to_scale])

In [40]:
pca = PCA(n_components=2)
pca.fit(df[features_to_scale])

PCA(n_components=2)

In [41]:
transformed_data = pca.transform(df[features_to_scale])

In [42]:
transformed_data

array([[-1.53724643,  0.41868622],
       [-1.51001032, -0.80111258],
       [ 1.09695264,  1.53736428],
       [ 1.95030411, -1.15493792]])

In [43]:
df

Company   Revenue    Profit  Market Share  Growth Rate
0       A -1.126221 -0.252198      0.074239    -1.434128
1       B -0.354827 -1.365960     -1.206470    -0.395626
2       C -0.128089  0.192099      1.540268     1.152319
3       D  1.609136  1.426060     -0.408036     0.677435

### Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1.

In [45]:
df = pd.DataFrame({
    'values': [1,5,10,15,20]
})
df

values
0       1
1       5
2      10
3      15
4      20

In [48]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1,1))

In [50]:
scaler.fit_transform(df[['values']])

array([[-1.        ],
       [-0.57894737],
       [-0.05263158],
       [ 0.47368421],
       [ 1.        ]])

In [52]:
df_scaled = pd.DataFrame(scaler.fit_transform(df[['values']]), columns = ['scaled_values'])

In [54]:
pd.concat([df, df_scaled], axis = 1)

values  scaled_values
0       1      -1.000000
1       5      -0.578947
2      10      -0.052632
3      15       0.473684
4      20       1.000000

### Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [ ]:
'''
The number of principal components to retain in a Principal Component Analysis (PCA) depends on the specific goals of your analysis and the trade-off between dimensionality reduction and information preservation. Here are the general steps to decide how many principal components to retain:

1. Standardize your data: Before performing PCA, it's important to standardize or normalize your data so that all features have the same scale. This is crucial because PCA is sensitive to the scale of the variables.

2. Calculate the covariance matrix: Compute the covariance matrix of your standardized data. The covariance matrix will help you understand how the features are correlated with each other.

3. Perform eigendecomposition: Perform eigendecomposition on the covariance matrix to obtain the eigenvalues and eigenvectors.

4. Sort eigenvalues: Sort the eigenvalues in descending order. The eigenvalues represent the amount of variance explained by each principal component.

5. Explained Variance: Calculate the cumulative explained variance for each number of retained principal components. This helps you understand how much variance is retained as you increase the number of components.

6. Decide the number of components: There are several methods to decide how many principal components to retain:

   a. Explained Variance Threshold: You can set a threshold (e.g., 95% or 99% explained variance) and retain enough principal components to exceed that threshold.

   b. Scree Plot: Plot the eigenvalues and look for an "elbow point" in the scree plot. The eigenvalues before the elbow point explain the most significant variance.

   c. Cross-validation: Use cross-validation techniques to evaluate the performance of your model with different numbers of components and choose the one that gives the best results.

   d. Business/domain knowledge: Sometimes, domain knowledge or specific requirements may dictate the number of components to retain.

Without knowing the actual data and its characteristics, it's challenging to provide an exact number of principal components to retain. However, you would typically start by looking at the explained variance, as it tells you how much information you can preserve with each component. If, for example, you find that retaining 95% of the explained variance requires only three principal components, you might choose to retain those three to reduce dimensionality while preserving most of the information.

It's essential to strike a balance between dimensionality reduction and information preservation. Retaining too few components may lead to a loss of important information, while retaining too many components may not provide significant benefits in terms of reducing dimensionality. The choice of the number of principal components should be guided by the specific needs and goals of your analysis.
'''