#### Consider the below code to answer further questions:

In [1]:
import numpy as np

In [2]:
list_ = ['1','2','3','4','5']
array_list = np.array(object=list_)

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

In [9]:
array_list.dtype

dtype('<U1')

- There is no difference in the data types of both the variables.
- Both the variables have string data types.
- Only difference between them is one is list and other is numpy array.

### Q2. Write a code to print the data type of each and every element of both the variables list_ and arra_list.

In [12]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [13]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


### Q3. Considering the following changes in the variable, array_list:

In [14]:
array_list = np.array(object = list_, dtype = int)

#### Will there be any difference in the data type of the elements present in both the variables, list_ and arra_list? If so then print the data types of each and every element present in both the variables, list_ and arra_list.

In [15]:
list_

['1', '2', '3', '4', '5']

In [16]:
array_list

array([1, 2, 3, 4, 5])

In [17]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [19]:
for i in array_list:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


#### Consider the below code to answer further questions:

In [20]:
import numpy as np

In [21]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object=num_list)

In [22]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

### Q4. Write a code to find the following characteristics of variable, num_array:
#### (i) shape
#### (ii) size

In [24]:
num_array.shape

(2, 3)

In [25]:
num_array.size

6

### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array creation function.
#### [Hint: The size of the array will be 9 and the shape will be (3,3).]

In [26]:
my_array = np.zeros((3,3))

In [27]:
my_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
my_array.shape

(3, 3)

In [29]:
my_array.size

9

### Q6. Create an identity matrix of shape (5,5) using numpy functions?
#### [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [33]:
my_matrix = np.eye(5)

In [34]:
my_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])